### ISSUE TITLE
Multi hit final hit - Compatibility request

### ISSUE THREAD

**Issue by ShadowsFang** [Felscream/DragoonMayCry#20] opened 2024-10-08 22:57 UTC
Can you make this work with the multihit plugin? Since the gauge increases based on damage fly text then it doubles up when you have the "final hit" setting enabled.

**Comment by Felscream** [comment] 2024-10-08 23:21
I thought it would be simple to resolve when I read you request but the available options in MultiHit do not allow me to identify the final hit reliably. The `#hitNumber` cannot be tracked since users can disable it. 
Another difficulty is to differentiate jobs or actions with a multi hit entry configured from other jobs and actions that are not configured.

The only "workaround" I have found is to enable "Interruptible" for each multi hit entry, it seems to prevent the delayed final hit from appearing if you use another action that generates a fly text.

**Comment by Felscream** [comment] 2024-10-22 10:01
I just tested it today and the behaviour isn't reproducible anymore. I'll close this issue tomorrow. 
The letter will shake with each hit, but the bar doesn't seem to grow twice with the "Show final option" activated on multi hit.

**Comment by Felscream** [comment] 2024-10-24 07:27
Not reproducible with multi hit 0.0.2.2

**Closed as not planned by Felscream** 2024-10-24 07:27 UTC
Labels: bug, question
